/// Flutter icons Stopwatch
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Stopwatch
///      fonts:
///       - asset: fonts/Stopwatch.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Stopwatch {
  Stopwatch._();

  static const _kFontFam = 'Stopwatch';
  static const String? _kFontPkg = null;

  static const IconData stopwatch = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
