/// Flutter icons WorldClock
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WorldClock
///      fonts:
///       - asset: fonts/WorldClock.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WorldClock {
  WorldClock._();

  static const _kFontFam = 'WorldClock';
  static const String? _kFontPkg = null;

  static const IconData worldClock = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
